### ISSUE TITLE
I would like prefer get to work universally.

### ISSUE THREAD

**Issue by calekennedy** [wix/eslint-plugin-lodash#100]
This is a feature request.

The prefer-get rule should be able to be universally applied.

For instance, right now this will only complain if the code includes something like 

```
(a.b && a.b.c)
```

But it would be nice to be able to enforce this same rule in situations like
```
const myVar = a.b.c;
```
This style commonly results in a cannot read property of undefined error.
Using lint to detect these potential points of failure would be beneficial.

**Comment by mik01aj** [comment]
@calekennedy what happens if you set `"lodash/prefer-get": ["warn", 1]` in your `.eslintrc`?

And, well, should the rule warn also in these cases?

```
document.getElementById('x') // getElementById might be null
object.someString.length === 4 // someString might be null
```

**Comment by calekennedy** [comment]
If I use ```"lodash/prefer-get": ["warn", 1]```, I get the following:

`Configuration for rule "lodash/prefer-get" is invalid: Value "1" is less than minimum.`

**Comment by mik01aj** [comment]
Hmm. The more *I* think about this, the more I consider this a terrible idea.

Apparently you're trying to make a rule that would guard you from exceptions where something that is normally an object, happens to be null. And you want to change dots to usages of `_.get` so that you don't get these exceptions anymore.

Well, other languages (e.g. coffeescript, groovy, C#6) have a remedy for that, and it's called [Safe navigation operator](https://en.wikipedia.org/wiki/Safe_navigation_operator), `?.`. Note that this is a new operator, and does not replace the standard `.` operator. Why? I found a [comment on HN](https://news.ycombinator.com/item?id=12216596) that summarizes my point pretty well:

> Slight aside: please don't abuse the Elvis operator like that (by using it on every single nullable reference), it could easily grow into a widespread anti-pattern that makes debugging harder.
My rule of thumb is that ?. is OK to use when

>1) The reference is expected to occasionally be null in the course of normal operations

> 2) You legitimately don't care if the reference is unexpectedly null, as you wouldn't or couldn't fix it even if you knew about it

> Otherwise it's better to discover and fix the NullReferenceException ASAP.

The thing is, there is no easy recipe to get rid of all null-related bugs. Somethimes it's correct to ignore the null, and sometimes the null means something that Really Shouldn't Happen. And you, the programmer, should know that. No eslint plugin will ever know that because this is a part of your business logic.

**Comment by ganimomer** [comment]
I agree with @mik01aj here.
This rule's purpose is to change the same operation to a more succinct form.
Without Lodash, the usual way of knowing that an entire path exists is in the form `a && a.b && a.b.c ...`, and all Lodash allows is to change that to `_.get(a, 'b.c')`.
I don't think the rule should just warn on member accesses, because in most cases the programmer should know their data enough to know whether to check for that case or not. 
(For instance, client-side code can pretty much always assume `document.location.href` exists)

**Comment by jfmengels** [comment]
Additionally, if you wanted this rule to enforce using `_.get` instead of accessing a property natively, then you'd get an error because you'd need to use `_.get` to access the `get` property of `_`...
