### ISSUE TITLE
False positive `prefer-lodash-method` rule when calling any function with the same name as some lodash function name

### ISSUE THREAD

**Issue by misino** [wix/eslint-plugin-lodash#129]
The rule is triggered for all internal or external libraries which contain functions of the same name as lodash function.

For example:
`import {mount} from "enzyme";`
`const wrapper = mount(<MyComponent />)";`
`wrapper.find("input");` **// calling this method falsely triggers prefer-lodash-method rule**

**Comment by ganimomer** [comment]
Hi,
Since there's no feasible way to know that `find` isn't used as an array function, There's no way for ESLint to tell between this `find` and the native `find`.

To solve this, [the rule has the `ignoreMethods` configuration option](https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/prefer-lodash-method.md). 
You can configure the rule to ignore `find` in the folder/files with enzyme tests.
