### ISSUE TITLE
'Replace' prefer-lodash-method acting out on a Class function

### ISSUE THREAD

**Issue by wubzz** [wix/eslint-plugin-lodash#139]
I was scratching my head until i realized what was going on, but basically this will give a linting error:

```javascript
class Test {
	static replace() {
		console.log('I do nothing');
	}
}

Test.replace();
```

`Prefer '_.replace' over the native function  lodash/prefer-lodash-method`

I'm not sure how far the plugin can go in detecting this, but I figured I'd report it just in case. Using 2.3.6.

**Comment by skratchdot** [comment]
@wubzz - I was concerned this would start happening.  For the time being, can you add `replace` to the configuration object `ignoredMethods`, and see if your issue is resolved?

I'd like to figure out a way to check that string methods are only being called on strings, but that might be difficult to get 100% right.

**Comment by skratchdot** [comment]
i.e. something like:

```
"lodash/prefer-lodash-method": [2, {"ignoreMethods": ["replace"]}]
```

**Comment by ganimomer** [comment]
Hi,
Like @skratchdot said, there currently isn't any way to detect whether the `replace` is native or a static method, and `ignoreMethods` is the way to go.
