### ISSUE TITLE
[q] list of 'must have' options to force migration from 3rd to 4th version of lodash

### ISSUE THREAD

**Issue by ZuBB** [wix/eslint-plugin-lodash#41]
Hi there!

Is there any list of options that need to be used to show end user what statements need to be updated when migration from 3rd to 4th version of lodash is in progress?

Thanks

**Comment by ganimomer** [comment]
Hi,
Let's start with a disclaimer: the plugin **is not enough to migrate Lodash versions**. 
It won't catch the cases of lodash functions that have ceased to exist, like `_.pluck`. Also, with some of the breaking changes, there's no replacement for going over the release notes and going over your code. (e.g. `_.rest` is a method in both versions that does completely different things).

Having said that, here are the rules that are expected to alert you upon migration (if you make sure the plugin is not configured to work with v3)

* `callback-binding` will report on all cases when you used `thisArg` for methods when it doesn't exist.
* `no-extra-args`: will report for all the methods that have a fixed number of arguments, if you used superfluous arguments.
* `unwrap` and `no-double-unwrap` will report on the cases where functions changed their chaining behaviour (e.g. `forEach`, that breaks the chain in v4 but not in v3).
* `preferred-alias` makes sure you use the main alias for methods, and is version dependant, so, for instance it will report when you use `first` instead of `head`.

Besides that, I'd recommend you go through the rule descriptions in the README and see which ones you'd like to enforce.

**Comment by ZuBB** [comment]
Thanks for reply
