### ISSUE TITLE
Rule proposal: prefer-includes

### ISSUE THREAD

**Issue by captbaritone** [wix/eslint-plugin-lodash#46]
In my [Underscore fork](https://github.com/captbaritone/eslint-plugin-underscore) I'm working on a rule `prefer-contains` that warns if you try to check if the result of `_.indexOf` is negative. For example:

    _.indexOf(collection, item) !== -1

In this case it's better to use `_.includes` (or in Underscore `_.contains`):

    _.includes(collection, item)

I found about 30 instances of this pattern in our code base, so it may be a common pattern among Lodash users as well.

**Comment by ganimomer** [comment]
Hi,
This sounds like a good idea! What about optionally warning also on native `indexOf`, though? 
Unless I'm wrong, it would cover more cases, since `_.indexOf` only works on collections, but `_.includes` also works the same as `String.prototype.includes` does in ES2016, and there's no native ESLint rule recommending the replacement at the moment, so it wouldn't clash.

You're welcome to read the discussions we had about `_.indexOf` before, in #11.
