### ISSUE TITLE
enhancement: add option for matches-prop-shorthand to only warn on literals

### ISSUE THREAD

**Issue by lukeapage** [wix/eslint-plugin-lodash#48]
the following gets a warning from matches-prop-shorthand
```
var a = _.filter(b, function(c) {
   return c.d === e;
});
```
but if `e` is not a literal or variable containing a literal then switching to the matches prop shorthand will change behaviour (e.g. for an example...)
```
var e = {};
var b = [{d:{}}];
var a = _.filter(b, function(c) {
   return c.d === e;
});
// a === undefined
var a = _.filter(b, ['d', e]);
// a === b[0]
```
So.. I'd rather only have this rule on if it is being compared against a literal, to avoid "tricking" a developer not thinking about it into changing the behaviour of the program...

**Comment by lukeapage** [comment]
I propose a new value 'alwaysLiterals' (or 'literals' ?) - if you agree I can make a pr

**Comment by ganimomer** [comment]
Hi,
I see your point - `_.matchesProp` (and the shorthand) compares values using `_.isEqual` rather than strict equality, and this would alter behaviour in this case.
However, the trade-off here is that this setting would not warn on variables, which I think is a much more common case than checking equality of object references.

We've used this plugin here on a pretty large code base for a long time, and I don't know of a case where this affected the result, so I can't say it would be a priority for us, but you're welcome to submit a PR.
I think this could be an extra option that would have to be turned on explicitly, like:
```json
{
  "lodash/matches-prop-shorthand": [2, "always", {"onlyLiterals":true}]
}
```
